config/routes.rb
Rails.application.routes.draw do
  resources :videos
  root 'pages#home'
  get 'pages/videos'
  get 'videos/videos'

end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  def videos
    @video = Video.all
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.order("RANDOM()").limit(1)
    @video = Video.all
  end
  def videos
    @video = Video.all
  end
  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:url, :artist, :song, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MissingFeed</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Varela+Round|Montserrat:400,700" type="text/css">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
  <%= favicon_link_tag 'faviconmf.ico' %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/pages/home.html.haml
.home
  .home_wrapper
    .logo
      %h1 MSNGFD
      %h5 music videos missing from your life
    .push_play
      = link_to videos_path do
        %i.fa.fa-play

app/views/pages/videos.html.haml
.header
  .header_info
    .logo
      %h1= link_to "MSNGFD", root_path
  .info
    %h4 created & curated by
    %span
      %a{:href => "http://www.dwst.cc", :target => "_blank"} dwst
.back_button
  = link_to 'Back to Random', videos_path
.mobile_container_all
  - @video.reverse_each do |video|
    .video_wrapper_all
      .video_content
        %img.ratio{:src => "http://placehold.it/16x9"}/
        %iframe#player{:allowfullscreen => "", :frameborder => "0", :src => "https://www.youtube.com/embed/#{video.link}?rel=0&amp;amp;showinfo=0;enablejsapi=1"}
      .video_foot
        .video_info.all_foot
          = link_to video_path(video) do
            %h1.all_foot= ((video.artist)+'-'+(video.song))

app/views/videos/_form.html.haml
= form_for(@video) do |f|
  - if @video.errors.any?
    #error_explanation
      %h2
        = pluralize(@video.errors.count, "error")
        prohibited this video from being saved:
      %ul
        - @video.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :url
    %h5
      Paste in video id
      %span (https://www.youtube.com/watch?v=
      %span.bold s1oRf4TugIg
      %span )
    %br
      = f.text_field :link
  .field
    = f.label :artist
    %br
      = f.text_field :artist
  .field
    = f.label :song
    %br
      = f.text_field :song
  .form_buttons
    .actions
      = f.submit

app/views/videos/edit.html.haml
.mobile_container
  .new_form
    %h1 Editing Video
    = render 'form'
    .form_buttons
      .random_button
        = link_to 'Back', videos_path
        = link_to 'Show', @video
        = link_to 'Delete', @video, method: :delete, data: {confirm: "You sure?"}

app/views/videos/index.html.haml
.header
  .header_info
    .logo
      %h1= link_to "MSNGFD", root_path
  .info
    %h4 created & curated by
    %span
      %a{:href => "http://www.dwst.cc", :target => "_blank"} dwst
.mobile_container
  - @videos.each do |video|
    .video_wrapper
      .video_content
        %img.ratio{:src => "http://placehold.it/16x9"}/
        %iframe#player{:allowfullscreen => "", :frameborder => "0", :src => "https://www.youtube.com/embed/#{video.link}?rel=0&amp;amp;showinfo=0;autoplay=1;enablejsapi=1"}
      .video_foot
        .video_info
          %h1=video.artist
          %h1 -
          %h1=video.song
        .buttons
          .random_button
            = link_to "random video", videos_path
          .add_button
            = link_to "add video", new_video_path
          .showall_button
            = link_to "all videos", pages_videos_path

%script{:src => "https://www.youtube.com/iframe_api", :type => "text/javascript"}
:javascript
  var player;
  function onYouTubeIframeAPIReady() {
      player = new YT.Player('player', {
        events: {
          'onStateChange': onPlayerStateChange
        }
      });
  }

  function onPlayerStateChange(event) {
      if(event.data === 0) {
          location.reload (true);
      }
  }

app/views/videos/new.html.haml
.mobile_container
  .new_form
    %h1 New Video

    = render 'form'
    .form_buttons
      .random_button
        = link_to 'Back', videos_path

app/views/videos/show.html.haml
.header
  .header_info
    .logo
      %h1= link_to "MSNGFD", root_path
  .info
    %h4 created & curated by
    %span
      %a{:href => "http://www.dwst.cc", :target => "_blank"} dwst
.mobile_container
  .video_wrapper
    .video_content
      %img.ratio{:src => "http://placehold.it/16x9"}/
      %iframe#player{:allowfullscreen => "", :frameborder => "0", :src => "https://www.youtube.com/embed/#{@video.link}?rel=0&amp;amp;showinfo=0;enablejsapi=1"}
    .video_foot
      .video_info
        %h1= @video.artist
        %h1 -
        %h1= @video.song
    .user_links
      = link_to 'Edit', edit_video_path(@video)
      \#{link_to 'Back to Random', videos_path}
      \#{link_to 'Back to All', pages_videos_path}
      \#{link_to 'Add Another Video', new_video_path}

app/views/videos/videos.html.haml
.header
  .header_info
    .logo
      %h1= link_to "MSNGFD", root_path
  .info
    %h4 created & curated by
    %span
      %a{:href => "http://www.dwst.cc", :target => "_blank"} dwst
.back_button
  = link_to 'Back to Random', videos_path
.mobile_container_all
  - @video.each do |video|
    .video_wrapper_all
      .video_content
        %img.ratio{:src => "http://placehold.it/16x9"}/
        %iframe#player{:allowfullscreen => "", :frameborder => "0", :src => "#{video.link}?rel=0&amp;amp;showinfo=0;enablejsapi=1"}
      .video_foot
        = link_to 'video', videos_video_path(video)
        .video_info
          %h1
            = video.artist
          %h1 -
          %h1
            = video.song